Transform: AWS::Serverless-2016-10-31
Description: Vehicle detection mlops backend
Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
    Auth:
      AddDefaultAuthorizerToCorsPreflight: false
    GatewayResponses:
      DEFAULT_4XX:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
            Access-Control-Allow-Methods: "'OPTIONS,GET,PUT'"
            Access-Control-Allow-Headers: "'Content-Type,Authorization'"
      DEFAULT_5XX:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
            Access-Control-Allow-Methods: "'OPTIONS,GET,PUT'"
            Access-Control-Allow-Headers: "'Content-Type,Authorization'"
  Function:
    Runtime: python3.8
    Timeout: 30
    MemorySize: 128
Resources:
  CheckDeploymentStatus:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/check_status.check_deplyment_status
      Description: A function that gets app meta
      Role: '{{resolve:ssm:/vda/iam/lambdarole:1}}'
      CodeUri: s3://zvissh-us-east-1/v13/85bd36c6c7ef1b169161e6f2262beaa6
  DeployModel:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/deploy.deploy
      Description: A function that gets app meta
      Role: '{{resolve:ssm:/vda/iam/lambdarole:1}}'
      CodeUri: s3://zvissh-us-east-1/v13/85bd36c6c7ef1b169161e6f2262beaa6
